# Generated by Django 4.2.1 on 2023-06-22 13:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('python_meetupbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'verbose_name': 'Comment', 'verbose_name_plural': 'Comments'},
        ),
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='speakers',
            options={'verbose_name': 'Speaker', 'verbose_name_plural': 'Speakers'},
        ),
        migrations.AlterModelOptions(
            name='topics',
            options={'verbose_name': 'Topic', 'verbose_name_plural': 'Topics'},
        ),
        migrations.AddField(
            model_name='comments',
            name='comment',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Comment to the speaker'),
        ),
        migrations.AddField(
            model_name='comments',
            name='date',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='date_event', to='python_meetupbot.events'),
        ),
        migrations.AddField(
            model_name='comments',
            name='speaker_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='speaker', to='python_meetupbot.speakers'),
        ),
        migrations.AddField(
            model_name='comments',
            name='telegram_id',
            field=models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='td_id', to='python_meetupbot.users'),
        ),
        migrations.AddField(
            model_name='events',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date of the event'),
        ),
        migrations.AddField(
            model_name='events',
            name='end',
            field=models.TimeField(blank=True, null=True, verbose_name='Time end event'),
        ),
        migrations.AddField(
            model_name='events',
            name='start',
            field=models.TimeField(blank=True, null=True, verbose_name='Time start event'),
        ),
        migrations.AddField(
            model_name='speakers',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Email speaker'),
        ),
        migrations.AddField(
            model_name='speakers',
            name='fio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='FIO Speaker'),
        ),
        migrations.AddField(
            model_name='speakers',
            name='speaker_id',
            field=models.IntegerField(blank=True, default=False, null=True, verbose_name='Telegram id'),
        ),
        migrations.AddField(
            model_name='topics',
            name='end',
            field=models.TimeField(blank=True, null=True, verbose_name='Topic end time'),
        ),
        migrations.AddField(
            model_name='topics',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='python_meetupbot.events', verbose_name='Event'),
        ),
        migrations.AddField(
            model_name='topics',
            name='speaker',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='python_meetupbot.speakers', verbose_name='Speaker'),
        ),
        migrations.AddField(
            model_name='topics',
            name='start',
            field=models.TimeField(blank=True, null=True, verbose_name='Topic start time'),
        ),
        migrations.AddField(
            model_name='topics',
            name='title',
            field=models.CharField(max_length=300, null=True, verbose_name='Topic'),
        ),
        migrations.AlterField(
            model_name='users',
            name='telegram_id',
            field=models.IntegerField(default=False, unique=True),
        ),
    ]
