# Generated by Django 4.2.1 on 2023-06-24 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('python_meetupbot', '0002_alter_comments_options_alter_events_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='speakers',
            name='speaker_id',
        ),
        migrations.AddField(
            model_name='speakers',
            name='telegram_id',
            field=models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tg_id', to='python_meetupbot.users'),
        ),
    ]
