# Generated by Django 4.2.1 on 2023-06-25 08:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('python_meetupbot', '0004_events_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='event name'),
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question', models.CharField(blank=True, max_length=200, null=True, verbose_name='Question to the speaker')),
                ('date', models.ForeignKey(default=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='questions_date_event', to='python_meetupbot.events')),
                ('speaker_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='questions_speaker', to='python_meetupbot.speakers')),
                ('telegram_id', models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='questions_td_id', to='python_meetupbot.users')),
            ],
            options={
                'verbose_name': 'Question',
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.CreateModel(
            name='Eventcomments',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('meetup_comment', models.CharField(blank=True, max_length=200, null=True, verbose_name='Comment about meetup')),
                ('date', models.ForeignKey(default=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Event_comments_date', to='python_meetupbot.events')),
                ('telegram_id', models.ForeignKey(blank=True, default=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Event_comments_td_id', to='python_meetupbot.users')),
            ],
            options={
                'verbose_name': 'Meetup Comment',
                'verbose_name_plural': 'Meetup Comments',
            },
        ),
    ]
