# Generated by Django 4.2.1 on 2023-06-25 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('python_meetupbot', '0005_alter_events_name_questions_eventcomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventcomments',
            name='name',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Event_name', to='python_meetupbot.events'),
        ),
    ]
