# Generated by Django 4.2.1 on 2023-06-25 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('python_meetupbot', '0006_eventcomments_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='name',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='Eventname', to='python_meetupbot.events'),
        ),
    ]
